import Banner from "@/components/Banner"
import Footer from "@/components/Footer"
import Header from "@/components/Header"
import InfoCard from "@/components/InfoCard"
import LargeCard from "@/components/LargeCard"
import LivePlacesData from "@/components/LivePlacesData"
import largeImg from ".././assets/travel.jpg"
export const metadata = {
  title: 'Home | air bnb',
  description: 'Generated by create next app',
}
export default async function Home(){
  const res = await fetch('http://localhost:3000/api/search')
  const data = await res.json()
  return (
    <div className="">
   
      {/* Header */}
      <Header/>
      {/* Banner */}
       <Banner/>
      {/* main  */}
       <main className="max-w-full mx-auto px-8 md:px-16 ">
        <section className="pt-6 ">
           <h2 className="text-xl md:text-3xl font-semibold pb-4">Explore Nearby</h2>
       
            <div className="grid grid-cols-1 md:grid-cols-2  md:gap-6  lg:grid-cols-3 xl:grid-cols-4 gap-3 mt-4">
            {
            data?.map((item)=><InfoCard key={item.id} item={item}>

            </InfoCard>)
            
            }
            </div>
        </section>
         <section className="pt-6">
           <h2 className="text-4xl py-4">Live Anywhere</h2>
           <div>
            <LivePlacesData/>
           </div>
        </section>
        <section className="">
         <LargeCard 
          img={largeImg}
          title="The Greatest Outdoors"
          description="Wishlists curated by Airbnb"
          buttonText="Get inspired"
         />
        </section>
      </main>
      <Footer/>
    </div>
  )
}

